spring:
  application:
    name: Chat
server:
  port: 8547
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false
security:
  secret-key: AM-ME-2024-32309-1q2w3e4r5t6y7u8i9o0p
  token-expiration-days: 15