spring:
  application:
    name: Monitoring-Communication
  datasource:
    url: jdbc:mysql://localhost:3306/monitoring
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8543
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false
queue:
  name: data_queue
  device:
    name: device_queue
exchange:
  name: device_changes
security:
  secret-key: AM-ME-2024-32309-1q2w3e4r5t6y7u8i9o0p
  token-expiration-days: 15